language: python
python:
  - "2.7"
  - "3.6"
install:
  - sudo apt-get update
  - echo $TRAVIS_PYTHON_VERSION
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest pyyaml scipy numpy psutil six lightgbm requests scikit-learn scikit-image gdal=2.2.4 coveralls pytest-cov coverage=4.5.1 h5py
  - source activate test-environment
  - conda info -a
  - conda list
  - conda install pip
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://github.com/MarcYin/gp_emulator/archive/62f288792e1b24a12891fc0ad32896cb7cb5eda4.zip -O gp_emulator.zip;unzip gp_emulator.zip; rm gp_emulator.zip;mv gp_emulator* gp_emulator;cd gp_emulator;python setup.py install;cd ..;rm -rf gp_emulator
    else
      pip install gp_emulator==1.6.1
  - pip install coveralls
  - pip install codecov
script:
  # Output something every 10 minutes or Travis kills the job
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - py.test -s --cov
  #Killing background sleep loop
  - kill %1
  #- travis_wait 60 py.test -s --cov
  - coverage xml
after_success:
  - codecov
  - coveralls
  - test $TRAVIS_BRANCH = "master" && conda install conda-build && conda install anaconda-client && PKG_NAME=siac && USER=f0xy && OS=$TRAVIS_OS_NAME-64 && mkdir ~/conda-bld && conda config --set anaconda_upload no && export CONDA_BLD_PATH=~/conda-bld && export VERSION=`date +%Y.%m.%d` && conda build . -c conda-forge && ls -lah $CONDA_BLD_PATH/$OS && anaconda -t $CONDA_UPLOAD_TOKEN upload -u $USER -l nightly $(ls $CONDA_BLD_PATH/$OS/$PKG_NAME-$VERSION*.tar.bz2) --force
