language: python
python:
  - "2.7"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
install:
  - sudo apt-get update
  - echo $TRAVIS_PYTHON_VERSION
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytest pyyaml scipy numpy psutil six requests scikit-learn scikit-image 'gdal>=2.1,<2.4' pytest-cov coverage pip
  - source activate test-environment
  - conda info -a
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install https://github.com/MarcYin/gp_emulator/archive/master.zip;
    else
      pip install gp_emulator==1.6.1;
    fi
  - pip install lightgbm >=2.1.0 coveralls codecov
  - conda install conda-build anaconda-client
  - conda list
script:
  # Output something every 10 minutes or Travis kills the job
  - while sleep 9m; do echo "=====[ $SECONDS seconds still running ]====="; done &
  - py.test -s --cov
  #Killing background sleep loop
  - kill %1
  - coverage xml
  - export SIAC_VERSION=$TRAVIS_TAG
deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASS
  skip_existing: true
  on:
    tags: true
    branch: master
after_success:
  - codecov
  - coveralls
  - rm -rf SIAC/emus/*.pkl S2?_MSIL1C*.SAFE
  #- bash conda_upload.sh
  - if [ -z "$SIAC_VERSION" ]; then echo "No git tag was set skipping anaconda build"; else bash conda_upload.sh ; fi
